using System;
using System.Collections.Generic;
using Unity.Netcode;
using Unity.Netcode.Components;
using UnityEngine;
using UnityEngine.AI;
#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// Point d'auteur unique pour les personnages, items et fantomes. Les
/// personnages sont instancies au lancement; les items et fantomes servent de
/// source de bake pour leurs objets de scene interactifs.
/// </summary>
[DisallowMultipleComponent]
[AddComponentMenu("Lit/Scene Marker")]
public sealed class SceneMarker : MonoBehaviour
{
    public enum MarkerAssetType
    {
        Character = 0,
        Item = 1,
        Ghost = 2
    }

    private const float MaximumPersistedEnemyPositionOffset = 20f;

    [SerializeField] private MarkerAssetType assetType = MarkerAssetType.Character;
    [SerializeField] private CharacterData characterData;
    [SerializeField] private Item item;
    [SerializeField] private GhostData ghost;
    [SerializeField, HideInInspector] private string markerId;

    private static readonly Dictionary<string, SceneMarker> markersById = new Dictionary<string, SceneMarker>();

    private GameObject runtimeInstance;
    private bool loggedMissingWorldPrefab;
    private bool loggedNetworkParentWarning;

    public CharacterData CharacterData => characterData;
    public Item Item => item;
    public GhostData Ghost => ghost;
    public MarkerAssetType AssetType => assetType;
    public bool UsesCharacter => assetType == MarkerAssetType.Character;
    public bool UsesItem => assetType == MarkerAssetType.Item;
    public bool UsesGhost => assetType == MarkerAssetType.Ghost;
    public string MarkerId => markerId;
    public GameObject RuntimeInstance => runtimeInstance;

    private void Awake()
    {
        if (!UsesCharacter)
        {
            return;
        }

        RegisterMarker(this);
        EnsurePersistentState();
        NetcodePrefabRegistry.RegisterSceneMarker(this);
    }

    private void Start()
    {
        if (UsesCharacter)
        {
            TrySpawn();
        }
    }

    private void Update()
    {
        if (UsesCharacter)
        {
            TrySpawn();
        }
    }

    private void OnDestroy()
    {
        if (!UsesCharacter)
        {
            return;
        }

        UnregisterMarker(this);
        NetcodePrefabRegistry.UnregisterSceneMarker(this);
    }

    public void SetCharacterData(CharacterData data)
    {
        assetType = MarkerAssetType.Character;
        characterData = data;
        loggedMissingWorldPrefab = false;
    }

    public void SetItem(Item value)
    {
        assetType = MarkerAssetType.Item;
        item = value;
    }

    public void SetGhost(GhostData value)
    {
        assetType = MarkerAssetType.Ghost;
        ghost = value;
    }

    public GameObject ResolvePreviewPrefab()
    {
        if (UsesItem)
        {
            return item != null ? item.ResolveWorldPrefab() : null;
        }

        if (UsesGhost)
        {
            return ghost != null ? ghost.ResolveWorldPrefab() : null;
        }

        return characterData != null ? characterData.ResolveWorldPrefab() : null;
    }

    public static bool TryGetRegisteredMarker(string id, out SceneMarker marker)
    {
        marker = null;
        return !string.IsNullOrWhiteSpace(id) && markersById.TryGetValue(id, out marker) && marker != null;
    }

    /// <summary>Configures the root generated by a SceneMarker before it is spawned.</summary>
    public static void ConfigureSpawnedCharacter(GameObject instance, CharacterData data, string persistentId)
    {
        if (instance == null || data == null)
        {
            return;
        }

        CharacterInfo characterInfo = instance.GetComponent<CharacterInfo>();
        if (characterInfo == null)
        {
            characterInfo = instance.AddComponent<CharacterInfo>();
        }
        characterInfo.SetCharacterData(data);

        if (data.isEnemy)
        {
            CombatHealth health = instance.GetComponent<CombatHealth>();
            if (health == null)
            {
                health = instance.AddComponent<CombatHealth>();
            }
            int maxHp = data.ResolveMaxHp();
            health.SetHealth(maxHp, maxHp);

        }

        if (TryGetRegisteredMarker(persistentId, out SceneMarker marker))
        {
            marker.SetRuntimeInstance(instance);
        }
    }

    public void ApplyPersistedState(Vector3 position, Quaternion rotation, Vector3 scale, int currentHp, int maxHp, bool active)
    {
        if (runtimeInstance == null)
        {
            return;
        }

        bool hasInvalidEnemyPosition = characterData != null && characterData.isEnemy &&
            Vector3.Distance(position, transform.position) > MaximumPersistedEnemyPositionOffset;
        if (hasInvalidEnemyPosition)
        {
            Debug.LogWarning("[SceneMarker] Etat persistant ignore pour '" + name +
                             "' : position trop eloignee du marker | sauvegarde=" + position +
                             " | marker=" + transform.position + ".", this);
        }
        else
        {
            runtimeInstance.transform.SetPositionAndRotation(position, rotation);
            runtimeInstance.transform.localScale = scale;
        }
        CombatHealth health = runtimeInstance.GetComponent<CombatHealth>();
        if (health != null && maxHp > 0)
        {
            health.SetHealth(currentHp, maxHp);
        }

        runtimeInstance.SetActive(active);
    }

    private void TrySpawn()
    {
        if (runtimeInstance != null)
        {
            EnsureServerSpawned(runtimeInstance);
            return;
        }

        if (characterData == null)
        {
            return;
        }

        if (characterData.worldPrefab == null)
        {
            if (!loggedMissingWorldPrefab)
            {
                Debug.LogError($"[SceneMarker] '{name}' requires CharacterData.worldPrefab for '{characterData.name}'.", this);
                loggedMissingWorldPrefab = true;
            }
            return;
        }

        NetworkManager manager = NetworkManager.Singleton;
        if (manager != null && manager.IsListening && !manager.IsServer)
        {
            return;
        }

        runtimeInstance = NetcodePrefabRegistry.SpawnSceneMarkerCharacterInstance(
            markerId,
            characterData,
            transform.position,
            transform.rotation);
        EnsureServerSpawned(runtimeInstance);
        ValidateSpawnedEnemyNavigation(runtimeInstance);
    }

    private void EnsureServerSpawned(GameObject instance)
    {
        NetworkManager manager = NetworkManager.Singleton;
        if (instance == null || manager == null || !manager.IsListening || !manager.IsServer)
        {
            return;
        }

        NetworkObject networkObject = instance.GetComponent<NetworkObject>();
        if (networkObject != null && !networkObject.IsSpawned)
        {
            networkObject.Spawn(true);
        }

        NetworkObject markerNetworkObject = GetComponent<NetworkObject>();
        if (networkObject == null || markerNetworkObject == null || !networkObject.IsSpawned || !markerNetworkObject.IsSpawned)
        {
            if (!loggedNetworkParentWarning)
            {
                loggedNetworkParentWarning = true;
                Debug.LogWarning(
                    "[SceneMarker] Parentage Netcode differe pour '" + name +
                    "' : le NetworkObject du marker doit etre spawn avant celui du clone.",
                    this);
            }
            return;
        }

        if (networkObject.transform.parent != transform && !networkObject.TrySetParent(markerNetworkObject, true))
        {
            Debug.LogError("[SceneMarker] Parentage Netcode impossible pour '" + name + "'.", this);
        }

        NetworkTransform networkTransform = instance.GetComponent<NetworkTransform>();
        if (networkTransform != null)
        {
            networkTransform.SwitchTransformSpaceWhenParented = true;
            networkTransform.InLocalSpace = true;
        }
    }

    private void SetRuntimeInstance(GameObject instance)
    {
        runtimeInstance = instance;
        ValidateSpawnedEnemyNavigation(runtimeInstance);
    }

    private void ValidateSpawnedEnemyNavigation(GameObject instance)
    {
        if (instance == null || characterData == null || !characterData.isEnemy)
        {
            return;
        }

        NavMeshAgent agent = instance.GetComponent<NavMeshAgent>();
        if (agent == null)
        {
            Debug.LogWarning("[SceneMarker] Ennemi '" + name + "' sans NavMeshAgent: il restera statique.", this);
            return;
        }

        Vector3 offset = instance.transform.position - transform.position;
        if (offset.magnitude > 0.15f)
        {
            Debug.LogWarning("[SceneMarker] Pose de spawn incoherente pour '" + name +
                             "' | marker=" + transform.position + " | instance=" + instance.transform.position + ".", this);
        }

        int areaMask = agent.areaMask == 0 ? NavMesh.AllAreas : agent.areaMask;
        if (!NavMesh.SamplePosition(instance.transform.position, out NavMeshHit hit, 1.5f, areaMask))
        {
            Debug.LogError("[SceneMarker] Ennemi '" + name + "' hors NavMesh a son spawn: " +
                           instance.transform.position + ". Aucun repositionnement automatique ne sera applique.", this);
            return;
        }

        if (Vector3.Distance(hit.position, instance.transform.position) > 0.15f)
        {
            Debug.LogError("[SceneMarker] NavMesh trop eloigne pour '" + name + "' | actor=" +
                           instance.transform.position + " | nav=" + hit.position + ".", this);
        }
    }

    private void EnsurePersistentState()
    {
        if (string.IsNullOrWhiteSpace(markerId))
        {
            return;
        }

        if (GetComponent<PersistentSceneMarkerCharacterState>() == null)
        {
            gameObject.AddComponent<PersistentSceneMarkerCharacterState>();
        }

        PersistentNetworkObject persistentObject = NetcodeRuntimeUtilities.GetOrAdd<PersistentNetworkObject>(gameObject);
        persistentObject.AssignSceneIdentity(markerId);
    }

    private static void RegisterMarker(SceneMarker marker)
    {
        if (marker != null && !string.IsNullOrWhiteSpace(marker.markerId))
        {
            markersById[marker.markerId] = marker;
        }
    }

    private static void UnregisterMarker(SceneMarker marker)
    {
        if (marker != null && !string.IsNullOrWhiteSpace(marker.markerId) &&
            markersById.TryGetValue(marker.markerId, out SceneMarker registered) && registered == marker)
        {
            markersById.Remove(marker.markerId);
        }
    }

#if UNITY_EDITOR
    private void OnValidate()
    {
        if (Application.isPlaying)
        {
            return;
        }

        if (!UsesCharacter)
        {
            return;
        }

        string generatedId = PersistentIdUtility.GenerateSceneObjectId(gameObject);
        if (!string.IsNullOrWhiteSpace(generatedId) && !string.Equals(markerId, generatedId, StringComparison.Ordinal))
        {
            markerId = generatedId;
            EditorUtility.SetDirty(this);
        }
    }

    private void OnDrawGizmos()
    {
        DrawWorldPrefabGizmo(Selection.Contains(gameObject));
    }

    private void DrawWorldPrefabGizmo(bool selected)
    {
        GameObject worldPrefab = ResolvePreviewPrefab();
        if (worldPrefab == null)
        {
            return;
        }

        Renderer[] renderers = worldPrefab.GetComponentsInChildren<Renderer>(true);
        Bounds bounds = new Bounds(Vector3.zero, Vector3.zero);
        bool hasBounds = false;
        for (int i = 0; i < renderers.Length; i++)
        {
            Renderer renderer = renderers[i];
            if (renderer == null)
            {
                continue;
            }

            Bounds localBounds = renderer.localBounds;
            Matrix4x4 relativeMatrix = worldPrefab.transform.worldToLocalMatrix * renderer.transform.localToWorldMatrix;
            Vector3 center = relativeMatrix.MultiplyPoint3x4(localBounds.center);
            if (!hasBounds)
            {
                bounds = new Bounds(center, localBounds.size);
                hasBounds = true;
            }
            else
            {
                bounds.Encapsulate(center + localBounds.extents);
                bounds.Encapsulate(center - localBounds.extents);
            }
        }

        if (!hasBounds)
        {
            return;
        }

        Color previous = Gizmos.color;
        Matrix4x4 previousMatrix = Gizmos.matrix;
        Gizmos.color = selected ? new Color(1f, 0.65f, 0.15f, 1f) : new Color(0.15f, 0.85f, 1f, 0.95f);
        Gizmos.matrix = transform.localToWorldMatrix * Matrix4x4.TRS(Vector3.zero, worldPrefab.transform.localRotation, worldPrefab.transform.localScale);
        Gizmos.DrawWireCube(bounds.center, bounds.size);
        Gizmos.color = previous;
        Gizmos.matrix = previousMatrix;
    }
#endif
}
